name: L10n
on:
  push:
    branches:
    - master
    - generates_locales
    paths:
    - 'doc/**'
    - '!doc/locale/**'
jobs:
  generates_locales:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
        pre-build-command: pip install -r requirements.txt
        build-command: make gettext
    - name: Commit report
      run: |
          git config --global user.name 'Nextcloud Bot'
          git config --global user.email 'bot@nextcloud.com'
          git add -f doc/_build/locale
          git diff-index --quiet HEAD || git commit -am "Updates catalog templates (POT files fetched automatically by transifex)"
          git push
